# Generated by Django 4.2.18 on 2025-01-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.TextField()),
                ('password', models.TextField()),
            ],
        ),
    ]
