# Generated by Django 4.2.18 on 2025-02-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.CharField(max_length=300)),
                ('crust', models.CharField(choices=[('Normal', 'Normal'), ('Thin', 'Thin'), ('Thick', 'Thick'), ('Gluten-free', 'Gluten-free'), ('Cardboard', 'Cardboard')], default='Normal', max_length=300)),
                ('sauce', models.CharField(max_length=300)),
                ('cheese', models.CharField(max_length=300)),
                ('pepperoni', models.BooleanField(default=False)),
                ('chicken', models.BooleanField(default=False)),
                ('ham', models.BooleanField(default=False)),
                ('pineapple', models.BooleanField(default=False)),
                ('peppers', models.BooleanField(default=False)),
                ('mushrooms', models.BooleanField(default=False)),
                ('onions', models.BooleanField(default=False)),
            ],
        ),
    ]
