# Generated by Django 4.2.18 on 2025-01-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('ingredients', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
