# Generated by Django 4.2.18 on 2025-02-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0002_pizza_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='name',
        ),
        migrations.AddField(
            model_name='pizza',
            name='crust',
            field=models.CharField(choices=[('N', 'Normal'), ('t', 'Thin'), ('T', 'Thick'), ('NG', 'Gluten-free'), ('C', 'Cardboard')], default='Normal', max_length=300),
        ),
        migrations.AddField(
            model_name='pizza',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='Small', max_length=300),
        ),
    ]
