# Generated by Django 4.2.18 on 2025-02-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0002_cheeses_sauces_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='size',
            field=models.CharField(choices=[], max_length=300),
        ),
    ]
