# Generated by Django 4.2.18 on 2025-02-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0003_remove_pizza_ingredients_remove_pizza_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='cheese',
            field=models.CharField(choices=[('M', 'Mozzarella'), ('C', 'Cheddar'), ('V', 'Vegan'), ('L', 'Low fat')], default='Cheddar', max_length=300),
        ),
        migrations.AddField(
            model_name='pizza',
            name='sauce',
            field=models.CharField(choices=[('T', 'Tomato'), ('B', 'BBQ'), ('M', 'Mayonnaise')], default='Tomato', max_length=300),
        ),
        migrations.AddField(
            model_name='pizza',
            name='toppings',
            field=models.CharField(choices=[('P', 'Pepperoni'), ('C', 'Chicken'), ('H', 'Ham'), ('P', 'Pinapple'), ('Pp', 'Peppers'), ('M', 'Mushrooms'), ('O', 'Onions')], default='Pepperoni', max_length=300),
        ),
    ]
