# Generated by Django 4.2.18 on 2025-02-10 10:04

import datetime
from django.db import migrations, models
import pizza_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0003_alter_pizza_cheese_alter_pizza_sauce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='card_number',
            field=models.CharField(default='0000000000000000', max_length=16, validators=[pizza_app.models.validate_card]),
        ),
        migrations.AlterField(
            model_name='order',
            name='cvv',
            field=models.CharField(default='000', max_length=3, validators=[pizza_app.models.validate_cvv]),
        ),
        migrations.AlterField(
            model_name='order',
            name='exp_date',
            field=models.DateField(default=datetime.date.today, validators=[pizza_app.models.validate_date]),
        ),
    ]
