# Generated by Django 4.2.18 on 2025-02-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0003_alter_pizza_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='cheese',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='sauce',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='size',
        ),
        migrations.AddField(
            model_name='pizza',
            name='cheese',
            field=models.ManyToManyField(to='pizza_app.cheeses'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='sauce',
            field=models.ManyToManyField(to='pizza_app.sauces'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='size',
            field=models.ManyToManyField(to='pizza_app.sizes'),
        ),
    ]
