# Generated by Django 4.2.18 on 2025-02-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0004_alter_pizza_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='Negra Arroyo lane', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='card_number',
            field=models.CharField(default='0000000000000000', max_length=16),
        ),
        migrations.AddField(
            model_name='order',
            name='cvv',
            field=models.CharField(default='000', max_length=3),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='joe', max_length=50),
        ),
    ]
