# Generated by Django 4.2.18 on 2025-02-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0004_alter_order_card_number_alter_order_cvv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(default='A place far-far away...', max_length=300),
        ),
    ]
