# Generated by Django 4.2.18 on 2025-02-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0004_pizza_cheese_pizza_sauce_pizza_toppings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='toppings',
            field=models.CharField(choices=[('P', 'Pepperoni'), ('C', 'Chicken'), ('H', 'Ham'), ('Pa', 'Pinapple'), ('Pp', 'Peppers'), ('M', 'Mushrooms'), ('O', 'Onions')], default='Pepperoni', max_length=300),
        ),
    ]
