# Generated by Django 4.2.18 on 2025-02-09 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0005_order_address_order_card_number_order_cvv_order_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='order',
            name='exp_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
