# Generated by Django 4.2.18 on 2025-02-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0006_alter_pizza_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='cheese',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='sauce',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='size',
        ),
        migrations.AddField(
            model_name='pizza',
            name='cheese',
            field=models.CharField(choices=[('Mozzarella', 'Mozzarella'), ('Cheddar', 'Cheddar'), ('Low fat', 'Low fat'), ('Vegan', 'Vegan')], default='', max_length=300),
        ),
        migrations.AddField(
            model_name='pizza',
            name='sauce',
            field=models.CharField(choices=[('Tomato', 'Tomato'), ('BBQ', 'BBQ')], default='', max_length=300),
        ),
        migrations.AddField(
            model_name='pizza',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], default='', max_length=300),
        ),
    ]
