# Generated by Django 4.2.18 on 2025-02-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0007_remove_pizza_cheese_remove_pizza_sauce_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='sauce',
            field=models.CharField(choices=[('Tomato', 'Tomato'), ('BBQ', 'BBQ'), ('Pink sauce', 'Pink sauce')], default='', max_length=300),
        ),
    ]
