# Generated by Django 4.2.18 on 2025-02-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0008_alter_pizza_sauce'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='user',
            field=models.CharField(default='', max_length=300),
        ),
    ]
