# Generated by Django 4.2.18 on 2025-02-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0011_alter_pizza_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
