# Generated by Django 4.2.18 on 2025-02-07 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pizza_app', '0012_alter_pizza_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='user',
        ),
        migrations.AddField(
            model_name='pizza',
            name='owner',
            field=models.OneToOneField(default='none', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
