# Generated by Django 4.2.18 on 2025-02-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0016_remove_pizza_id_alter_pizza_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='owner',
        ),
        migrations.AddField(
            model_name='pizza',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pizza',
            name='user',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
